all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/master-key.pem
  
  children:
    master:
      hosts:
        ec2-master:
          ansible_host: 54.145.229.56   # IP from Terraform output
    workers:
      hosts:
        ec2-worker-1:
          ansible_host: 54.166.171.107