all:
  children:
    master:
      hosts:
    workers:
      hosts:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/multipass_id_rsa
    ansible_user: ubuntu
